// Curated Lucide set relevant to car attributes. Stored as full Iconify names
// so each drops straight into <UIcon :name>. All bundled by @iconify-json/lucide
// (no runtime fetch). Hand-picked — not the full set — to keep the picker fast.
export const LUCIDE_ATTRIBUTE_ICONS = [
  'i-lucide-snowflake',
  'i-lucide-sun',
  'i-lucide-wind',
  'i-lucide-thermometer',
  'i-lucide-settings-2',
  'i-lucide-gauge',
  'i-lucide-fuel',
  'i-lucide-zap',
  'i-lucide-battery-charging',
  'i-lucide-armchair',
  'i-lucide-music',
  'i-lucide-radio',
  'i-lucide-volume-2',
  'i-lucide-bluetooth',
  'i-lucide-wifi',
  'i-lucide-smartphone',
  'i-lucide-monitor',
  'i-lucide-camera',
  'i-lucide-video',
  'i-lucide-navigation',
  'i-lucide-map-pin',
  'i-lucide-shield',
  'i-lucide-shield-check',
  'i-lucide-lock',
  'i-lucide-key',
  'i-lucide-key-round',
  'i-lucide-circle-parking',
  'i-lucide-disc',
  'i-lucide-cog',
  'i-lucide-wrench',
  'i-lucide-car',
  'i-lucide-car-front',
  'i-lucide-door-open',
  'i-lucide-sofa',
  'i-lucide-lightbulb',
  'i-lucide-eye',
  'i-lucide-umbrella',
  'i-lucide-droplets',
  'i-lucide-sparkles',
  'i-lucide-star',
  'i-lucide-tag',
] as const
